services:
    topicpreview.manager:
        class: vse\topicpreview\core\topic_preview
        arguments:
            - @config
            - @dbal.conn
            - @user
            - %core.root_path%
